In [1]:
import pandas as pd
centrao_2002 = pd.read_csv('centrao_2003.csv')
centrao_2006 = pd.read_csv('centrao_2007.csv')
centrao_2010 = pd.read_csv('centrao_2011.csv')
centrao_2014 = pd.read_csv('centrao_2015.csv') 
centrao_2018 = pd.read_csv('centrao_2019.csv')
centrao_2022 = pd.read_csv('centrao_2022.csv')

In [2]:
nomes_centrao = pd.concat([centrao_2002, centrao_2006, centrao_2010, centrao_2014, centrao_2018, centrao_2022])
nomes_centrao = nomes_centrao.drop_duplicates(subset=['0'], keep='first')
nomes_centrao = nomes_centrao.reset_index(drop=True)
nomes_centrao

                         0  Unnamed: 0
0           Adauto Pereira         NaN
1            Adelor Vieira         NaN
2            Ademir Camilo         NaN
3              Adão Pretto         NaN
4              Afonso Hamm         NaN
...                    ...         ...
1418          Yandra Moura         NaN
1419       Yury do Paredão         NaN
1420       Zezinho Barbary         NaN
1421            Zé Adriano         NaN
1422  Zé Haroldo Cathedral         NaN

[1423 rows x 2 columns]

In [ ]:
# import pandas as pd
# eleicao_2022 = pd.read_csv('Eleicoes/votacao_candidato_munzona_2022/votacao_candidato_munzona_2022_BRASIL.csv', encoding='latin1', sep=';')
# eleicao_2022_deputados = eleicao_2022.loc[eleicao_2022['DS_CARGO'] == 'Deputado Federal']
# eleicao_2022_deputados

In [ ]:
# eleicao_2022_deputados.to_csv('Eleicoes/votacao_candidato_munzona_2022/eleicao_2022_deputados.csv')

In [ ]:
eleicao_2022_deputados = pd.read_csv('Eleicoes/votacao_candidato_munzona_2022/eleicao_2022_deputados.csv')

In [8]:
eleicao_grouped_2022 = eleicao_2022_deputados.groupby(['CD_MUNICIPIO','NM_URNA_CANDIDATO'])['QT_VOTOS_NOMINAIS'].sum().reset_index()

In [18]:
%pip install unidecode
import unidecode

# Normalize the names in centrao_2022

nomes_centrao['0'] = nomes_centrao['0'].astype(str).apply(unidecode.unidecode)
nomes_centrao['0'] = nomes_centrao['0'].str.strip()  # Remove leading and trailing spaces
nomes_centrao['0'] = nomes_centrao['0'].str.replace(r'\s+', ' ', regex=True)  # Normalize whitespace

# Normalize the names in merged_df_2022
eleicao_grouped_2022['NM_URNA_CANDIDATO'] = eleicao_grouped_2022['NM_URNA_CANDIDATO'].astype(str).apply(unidecode.unidecode)
eleicao_grouped_2022['NM_URNA_CANDIDATO'] = eleicao_grouped_2022['NM_URNA_CANDIDATO'].str.strip()  # Remove leading and trailing spaces
eleicao_grouped_2022['NM_URNA_CANDIDATO'] = eleicao_grouped_2022['NM_URNA_CANDIDATO'].str.replace(r'\s+', ' ', regex=True)  # Normalize whitespace

# Convert to uppercase for case-insensitive comparison
nomes_centrao['0'] = nomes_centrao['0'].str.upper()
eleicao_grouped_2022['NM_URNA_CANDIDATO'] = eleicao_grouped_2022['NM_URNA_CANDIDATO'].str.upper()

Requirement already satisfied: unidecode in c:\programming\envs\questions\lib\site-packages (1.4.0)
Note: you may need to restart the kernel to use updated packages.

In [19]:
eleicao_grouped_centrao_2022 = pd.merge(eleicao_grouped_2022, nomes_centrao, left_on='NM_URNA_CANDIDATO', right_on='0', how='inner')
total_votes_city_2022 = eleicao_grouped_2022.groupby('CD_MUNICIPIO')['QT_VOTOS_NOMINAIS'].sum()
centrao_votes_city_2022 = eleicao_grouped_centrao_2022.groupby('CD_MUNICIPIO')['QT_VOTOS_NOMINAIS'].sum()
indice_centrao_2022 = centrao_votes_city_2022 / total_votes_city_2022
indice_centrao_2022 = indice_centrao_2022.reset_index()
indice_centrao_2022

      CD_MUNICIPIO  QT_VOTOS_NOMINAIS
0               19           0.098435
1               35           0.135224
2               51           0.085123
3               78           0.367971
4               94           0.020904
...            ...                ...
5565         98990           0.299394
5566         99015           0.095763
5567         99031           0.152947
5568         99058           0.383479
5569         99074           0.482345

[5570 rows x 2 columns]

In [20]:
names_cd_city = eleicao_2022_deputados[['CD_MUNICIPIO','NM_MUNICIPIO', 'SG_UF']].drop_duplicates()
names_cd_city = names_cd_city.reset_index()

indice_centrao_2022 = pd.merge(indice_centrao_2022, names_cd_city, on='CD_MUNICIPIO', how='inner')
indice_centrao_2022 = indice_centrao_2022.drop(columns=['CD_MUNICIPIO', 'index'])
indice_centrao_2022

      QT_VOTOS_NOMINAIS           NM_MUNICIPIO SG_UF
0              0.098435          GUAJARÁ-MIRIM    RO
1              0.135224            PORTO VELHO    RO
2              0.085123              JI-PARANÁ    RO
3              0.367971              ARIQUEMES    RO
4              0.020904                 CACOAL    RO
...                 ...                    ...   ...
5565           0.299394              VILA RICA    MT
5566           0.095763               COMODORO    MT
5567           0.152947  FIGUEIRÓPOLIS D OESTE    MT
5568           0.383479      GUARANTÃ DO NORTE    MT
5569           0.482345               INDIAVAÍ    MT

[5570 rows x 3 columns]

In [21]:
indice_centrao_2022.to_csv('indice_centrao_2022.csv', index=False)

# 2018

In [ ]:
# eleicao_geral_2018 = pd.read_csv('Eleicoes/votacao_candidato_munzona_2018/votacao_candidato_munzona_2018_BRASIL.csv', encoding='latin1', sep=';')

FileNotFoundError: [Errno 2] No such file or directory: 'Eleicoes/votacao_candidato_munzona_2018/votacao_candidato_munzona_2018_BRASIL.csv'

In [ ]:
# eleicao_2018_deputados.loc[eleicao_2018_deputados['CD_MUNICIPIO'] == 99074].groupby('NM_URNA_CANDIDATO')['QT_VOTOS_NOMINAIS'].sum().reset_index().sort_values('QT_VOTOS_NOMINAIS', ascending=False)

    NM_URNA_CANDIDATO  QT_VOTOS_NOMINAIS
20        DR LEONARDO                639
3       ADRIANO SILVA                125
34   EZEQUIEL FONSECA                117
107    VICTÓRIO GALLI                 74
26       EDNA SAMPAIO                 38
..                ...                ...
1    ADEVALDO TAXISTA                  0
54       JOSAIR LOPES                  0
53   JOQUEBEDY MOURÃO                  0
52        JAIR CEGATI                  0
0        ADAUTON TUIM                  0

[110 rows x 2 columns]

In [ ]:
# eleicao_2018_deputados = eleicao_geral_2018[eleicao_geral_2018['DS_CARGO'] == 'Deputado Federal']
# eleicao_grouped_2018 = eleicao_2018_deputados.groupby(['CD_MUNICIPIO','NM_URNA_CANDIDATO'])['QT_VOTOS_NOMINAIS'].sum().reset_index()

In [ ]:
# eleicao_2018_deputados.to_csv('eleicao_2018_deputados.csv', index=False)

In [24]:
eleicao_2018_deputados = pd.read_csv('Eleicoes/votacao_candidato_munzona_2018/eleicao_2018_deputados.csv')

In [26]:
eleicao_grouped_2018 = eleicao_2018_deputados.groupby(['CD_MUNICIPIO','NM_URNA_CANDIDATO'])['QT_VOTOS_NOMINAIS'].sum().reset_index()
# Normalize the names in merged_df_2018
eleicao_grouped_2018['NM_URNA_CANDIDATO'] = eleicao_grouped_2018['NM_URNA_CANDIDATO'].astype(str).apply(unidecode.unidecode)
eleicao_grouped_2018['NM_URNA_CANDIDATO'] = eleicao_grouped_2018['NM_URNA_CANDIDATO'].str.strip()  # Remove leading and trailing spaces
  # Normalize whitespace
eleicao_grouped_2018['NM_URNA_CANDIDATO'] = eleicao_grouped_2018['NM_URNA_CANDIDATO'].str.upper()

In [27]:
eleicao_grouped_centrao_2018 = pd.merge(eleicao_grouped_2018, nomes_centrao, left_on='NM_URNA_CANDIDATO', right_on='0')
total_votes_city_2018 = eleicao_grouped_2018.groupby('CD_MUNICIPIO')['QT_VOTOS_NOMINAIS'].sum()
centrao_votes_city_2018 = eleicao_grouped_centrao_2018.groupby('CD_MUNICIPIO')['QT_VOTOS_NOMINAIS'].sum()
indice_centrao_2018 = centrao_votes_city_2018 / total_votes_city_2018
indice_centrao_2018 = indice_centrao_2018.reset_index()
indice_centrao_2018

      CD_MUNICIPIO  QT_VOTOS_NOMINAIS
0               19           0.287008
1               35           0.506758
2               51           0.117869
3               78           0.473398
4               94           0.203489
...            ...                ...
5565         98990           0.305783
5566         99015           0.405593
5567         99031           0.175457
5568         99058           0.591136
5569         99074           0.142979

[5570 rows x 2 columns]

In [28]:
names_cd_city_2018 = eleicao_2018_deputados[['CD_MUNICIPIO','NM_MUNICIPIO', 'SG_UF']].drop_duplicates()
names_cd_city_2018 = names_cd_city_2018.reset_index()

indice_centrao_2018 = pd.merge(indice_centrao_2018, names_cd_city_2018, on='CD_MUNICIPIO', how='inner')
indice_centrao_2018 = indice_centrao_2018.drop(columns=['CD_MUNICIPIO', 'index'])
indice_centrao_2018

      QT_VOTOS_NOMINAIS           NM_MUNICIPIO SG_UF
0              0.287008          GUAJARÁ-MIRIM    RO
1              0.506758            PORTO VELHO    RO
2              0.117869              JI-PARANÁ    RO
3              0.473398              ARIQUEMES    RO
4              0.203489                 CACOAL    RO
...                 ...                    ...   ...
5565           0.305783              VILA RICA    MT
5566           0.405593               COMODORO    MT
5567           0.175457  FIGUEIRÓPOLIS D OESTE    MT
5568           0.591136      GUARANTÃ DO NORTE    MT
5569           0.142979               INDIAVAÍ    MT

[5570 rows x 3 columns]

In [29]:
indice_centrao_2018.to_csv('indice_centrao_2018.csv')

# 2014

In [30]:
eleicao_geral_2014 = pd.read_csv('Eleicoes/votacao_candidato_munzona_2014/votacao_candidato_munzona_2014_BRASIL.csv', encoding='latin1', sep=';')

In [ ]:
# eleicao_2014_deputados = eleicao_geral_2014[eleicao_geral_2014['DS_CARGO'] == 'Deputado Federal']
# eleicao_2014_deputados.to_csv('Eleicoes/votacao_candidato_munzona_2014/eleicao_2014_deputados.csv')

In [ ]:
eleicao_2014_deputados = pd.read_csv('Eleicoes/votacao_candidato_munzona_2014/eleicao_2014_deputados.csv')

In [32]:
eleicao_grouped_2014 = eleicao_2014_deputados.groupby(['CD_MUNICIPIO','NM_URNA_CANDIDATO'])['QT_VOTOS_NOMINAIS'].sum().reset_index()
# Normalize the names in merged_df_2014
eleicao_grouped_2014['NM_URNA_CANDIDATO'] = eleicao_grouped_2014['NM_URNA_CANDIDATO'].astype(str).apply(unidecode.unidecode)
eleicao_grouped_2014['NM_URNA_CANDIDATO'] = eleicao_grouped_2014['NM_URNA_CANDIDATO'].str.strip()  # Remove leading and trailing spaces
eleicao_grouped_2014['NM_URNA_CANDIDATO'] = eleicao_grouped_2014['NM_URNA_CANDIDATO'].str.replace(r'\s+', ' ', regex=True)  # Normalize whitespace

# Convert to uppercase for case-insensitive compariso
eleicao_grouped_2014['NM_URNA_CANDIDATO'] = eleicao_grouped_2014['NM_URNA_CANDIDATO'].str.upper()

In [33]:
eleicao_grouped_centrao_2014 = pd.merge(eleicao_grouped_2014, nomes_centrao, left_on='NM_URNA_CANDIDATO', right_on='0')
total_votes_city_2014 = eleicao_grouped_2014.groupby('CD_MUNICIPIO')['QT_VOTOS_NOMINAIS'].sum()
centrao_votes_city_2014 = eleicao_grouped_centrao_2014.groupby('CD_MUNICIPIO')['QT_VOTOS_NOMINAIS'].sum()
indice_centrao_2014 = centrao_votes_city_2014 / total_votes_city_2014
indice_centrao_2014 = indice_centrao_2014.reset_index()
indice_centrao_2014

      CD_MUNICIPIO  QT_VOTOS_NOMINAIS
0               19           0.491999
1               35           0.507906
2               51           0.720806
3               78           0.234790
4               94           0.716085
...            ...                ...
5565         98990           0.510256
5566         99015           0.539976
5567         99031           0.835749
5568         99058           0.702138
5569         99074           0.864448

[5570 rows x 2 columns]

In [34]:
names_cd_city_2014 = eleicao_2014_deputados[['CD_MUNICIPIO','NM_MUNICIPIO', 'SG_UF']].drop_duplicates()
names_cd_city_2014 = names_cd_city_2014.reset_index()

indice_centrao_2014 = pd.merge(indice_centrao_2014, names_cd_city_2014, on='CD_MUNICIPIO', how='inner')
indice_centrao_2014 = indice_centrao_2014.drop(columns=['CD_MUNICIPIO', 'index'])
indice_centrao_2014

      QT_VOTOS_NOMINAIS           NM_MUNICIPIO SG_UF
0              0.491999          GUAJARÁ-MIRIM    RO
1              0.507906            PORTO VELHO    RO
2              0.720806              JI-PARANÁ    RO
3              0.234790              ARIQUEMES    RO
4              0.716085                 CACOAL    RO
...                 ...                    ...   ...
5565           0.510256              VILA RICA    MT
5566           0.539976               COMODORO    MT
5567           0.835749  FIGUEIRÓPOLIS D OESTE    MT
5568           0.702138      GUARANTÃ DO NORTE    MT
5569           0.864448               INDIAVAÍ    MT

[5570 rows x 3 columns]

# 2010

In [ ]:
# eleicao_geral_2010 = pd.read_csv('Eleicoes/votacao_candidato_munzona_2010/votacao_candidato_munzona_2010_BRASIL.csv', encoding='latin1', sep=';')
# eleicao_2010_deputados = eleicao_geral_2010[eleicao_geral_2010['DS_CARGO'] == 'Deputado Federal']
# eleicao_2010_deputados.to_csv('Eleicoes/votacao_candidato_munzona_2010/eleicao_2010_deputados.csv')

In [ ]:
eleicao_2010_deputados = pd.read_csv('Eleicoes/votacao_candidato_munzona_2010/eleicao_2010_deputados.csv')

In [ ]:

eleicao_grouped_2010 = eleicao_2010_deputados.groupby(['CD_MUNICIPIO','NM_URNA_CANDIDATO'])['QT_VOTOS_NOMINAIS'].sum().reset_index()



# Normalize the names in eleicao_grouped_2010
eleicao_grouped_2010['NM_URNA_CANDIDATO'] = eleicao_grouped_2010['NM_URNA_CANDIDATO'].astype(str).apply(unidecode.unidecode)
eleicao_grouped_2010['NM_URNA_CANDIDATO'] = eleicao_grouped_2010['NM_URNA_CANDIDATO'].str.strip()  # Remove leading and trailing spaces
eleicao_grouped_2010['NM_URNA_CANDIDATO'] = eleicao_grouped_2010['NM_URNA_CANDIDATO'].str.upper()

# Merge and calculate indices
eleicao_grouped_centrao_2010 = pd.merge(eleicao_grouped_2010, nomes_centrao, left_on='NM_URNA_CANDIDATO', right_on='0')
total_votes_city_2010 = eleicao_grouped_2010.groupby('CD_MUNICIPIO')['QT_VOTOS_NOMINAIS'].sum()
centrao_votes_city_2010 = eleicao_grouped_centrao_2010.groupby('CD_MUNICIPIO')['QT_VOTOS_NOMINAIS'].sum()
indice_centrao_2010 = centrao_votes_city_2010 / total_votes_city_2010
indice_centrao_2010 = indice_centrao_2010.reset_index()

# Merge with city names
names_cd_city_2010 = eleicao_2010_deputados[['CD_MUNICIPIO','NM_MUNICIPIO', 'SG_UF']].drop_duplicates()
names_cd_city_2010 = names_cd_city_2010.reset_index()
9
indice_centrao_2010 = pd.merge(indice_centrao_2010, names_cd_city_2010, on='CD_MUNICIPIO', how='inner')
indice_centrao_2010 = indice_centrao_2010.drop(columns=['CD_MUNICIPIO', 'index'])
indice_centrao_2010

      QT_VOTOS_NOMINAIS           NM_MUNICIPIO SG_UF
0              0.497594          GUAJARÁ-MIRIM    RO
1              0.300329            PORTO VELHO    RO
2              0.423013              JI-PARANÁ    RO
3              0.480018              ARIQUEMES    RO
4              0.633694                 CACOAL    RO
...                 ...                    ...   ...
5562           0.508764              VILA RICA    MT
5563           0.561014               COMODORO    MT
5564           0.576658  FIGUEIRÓPOLIS D OESTE    MT
5565           0.551234      GUARANTÃ DO NORTE    MT
5566           0.729844               INDIAVAÍ    MT

[5567 rows x 3 columns]

In [38]:
indice_centrao_2010.to_csv('indice_centrao_2010.csv')

# 2006

In [ ]:
# eleicao_geral_2006 = pd.read_csv('Eleicoes/votacao_candidato_munzona_2006/votacao_candidato_munzona_2006_BRASIL.csv', encoding='latin1', sep=';')
# eleicao_2006_deputados = eleicao_geral_2006[eleicao_geral_2006['DS_CARGO'] == 'Deputado Federal']
# eleicao_2006_deputados.to_csv('Eleicoes/votacao_candidato_munzona_2006/eleicao_2006_deputados.csv')

In [ ]:
eleicao_2006_deputados = pd.read_csv('Eleicoes/votacao_candidato_munzona_2006/eleicao_2006_deputados.csv')

In [40]:
eleicao_grouped_2006 = eleicao_2006_deputados.groupby(['CD_MUNICIPIO','NM_URNA_CANDIDATO'])['QT_VOTOS_NOMINAIS'].sum().reset_index()
# Normalize the names in eleicao_grouped_2006
eleicao_grouped_2006['NM_URNA_CANDIDATO'] = eleicao_grouped_2006['NM_URNA_CANDIDATO'].astype(str).apply(unidecode.unidecode)
eleicao_grouped_2006['NM_URNA_CANDIDATO'] = eleicao_grouped_2006['NM_URNA_CANDIDATO'].str.strip()  # Remove leading and trailing spaces
eleicao_grouped_2006['NM_URNA_CANDIDATO'] = eleicao_grouped_2006['NM_URNA_CANDIDATO'].str.replace(r'\s+', ' ', regex=True)  # Normalize whitespace

# Convert to uppercase for case-insensitive comparison

eleicao_grouped_2006['NM_URNA_CANDIDATO'] = eleicao_grouped_2006['NM_URNA_CANDIDATO'].str.upper()

# Merge and calculate indices
eleicao_grouped_centrao_2006 = pd.merge(eleicao_grouped_2006, nomes_centrao, left_on='NM_URNA_CANDIDATO', right_on='0')
total_votes_city_2006 = eleicao_grouped_2006.groupby('CD_MUNICIPIO')['QT_VOTOS_NOMINAIS'].sum()
centrao_votes_city_2006 = eleicao_grouped_centrao_2006.groupby('CD_MUNICIPIO')['QT_VOTOS_NOMINAIS'].sum()
indice_centrao_2006 = centrao_votes_city_2006 / total_votes_city_2006
indice_centrao_2006 = indice_centrao_2006.reset_index()

# Merge with city names
names_cd_city_2006 = eleicao_2006_deputados[['CD_MUNICIPIO','NM_MUNICIPIO', 'SG_UF']].drop_duplicates()
names_cd_city_2006 = names_cd_city_2006.reset_index()

indice_centrao_2006 = pd.merge(indice_centrao_2006, names_cd_city_2006, on='CD_MUNICIPIO', how='inner')
indice_centrao_2006 = indice_centrao_2006.drop(columns=['CD_MUNICIPIO', 'index'])
indice_centrao_2006

      QT_VOTOS_NOMINAIS           NM_MUNICIPIO SG_UF
0              0.202692          GUAJARÁ-MIRIM    RO
1              0.286010            PORTO VELHO    RO
2              0.415607              JI-PARANÁ    RO
3              0.305006              ARIQUEMES    RO
4              0.290934                 CACOAL    RO
...                 ...                    ...   ...
5560           0.749908              VILA RICA    MT
5561           0.813568               COMODORO    MT
5562           0.682683  FIGUEIRÓPOLIS D OESTE    MT
5563           0.360208      GUARANTÃ DO NORTE    MT
5564           0.714832               INDIAVAÍ    MT

[5565 rows x 3 columns]

In [41]:
indice_centrao_2006.to_csv('indice_centrao_2006.csv')

# 2002

In [ ]:
# eleicao_geral_2002 = pd.read_csv('Eleicoes/votacao_candidato_munzona_2002/votacao_candidato_munzona_2002_BRASIL.csv', encoding='latin1', sep=';')
# eleicao_2002_deputados = eleicao_geral_2002[eleicao_geral_2002['DS_CARGO'] == 'Deputado Federal']
# eleicao_2002_deputados.to_csv('Eleicoes/votacao_candidato_munzona_2002/eleicao_2002_deputados.csv')

In [ ]:
eleicao_2002_deputados = pd.read_csv('Eleicoes/votacao_candidato_munzona_2002/eleicao_2002_deputados.csv')

In [44]:

eleicao_grouped_2002 = eleicao_2002_deputados.groupby(['CD_MUNICIPIO','NM_URNA_CANDIDATO'])['QT_VOTOS_NOMINAIS'].sum().reset_index()
# Normalize the names in eleicao_grouped_2002
eleicao_grouped_2002['NM_URNA_CANDIDATO'] = eleicao_grouped_2002['NM_URNA_CANDIDATO'].astype(str).apply(unidecode.unidecode)
eleicao_grouped_2002['NM_URNA_CANDIDATO'] = eleicao_grouped_2002['NM_URNA_CANDIDATO'].str.strip()  # Remove leading and trailing spaces
eleicao_grouped_2002['NM_URNA_CANDIDATO'] = eleicao_grouped_2002['NM_URNA_CANDIDATO'].str.replace(r'\s+', ' ', regex=True)  # Normalize whitespace

eleicao_grouped_2002['NM_URNA_CANDIDATO'] = eleicao_grouped_2002['NM_URNA_CANDIDATO'].str.upper()

# Merge and calculate indices
eleicao_grouped_centrao_2002 = pd.merge(eleicao_grouped_2002, nomes_centrao, left_on='NM_URNA_CANDIDATO', right_on='0')
total_votes_city_2002 = eleicao_grouped_2002.groupby('CD_MUNICIPIO')['QT_VOTOS_NOMINAIS'].sum()
centrao_votes_city_2002 = eleicao_grouped_centrao_2002.groupby('CD_MUNICIPIO')['QT_VOTOS_NOMINAIS'].sum()
indice_centrao_2002 = centrao_votes_city_2002 / total_votes_city_2002
indice_centrao_2002 = indice_centrao_2002.reset_index()

# Merge with city names
names_cd_city_2002 = eleicao_2002_deputados[['CD_MUNICIPIO','NM_MUNICIPIO', 'SG_UF']].drop_duplicates()
names_cd_city_2002 = names_cd_city_2002.reset_index()

indice_centrao_2002 = pd.merge(indice_centrao_2002, names_cd_city_2002, on='CD_MUNICIPIO', how='inner')
indice_centrao_2002 = indice_centrao_2002.drop(columns=['CD_MUNICIPIO', 'index'])
indice_centrao_2002

      QT_VOTOS_NOMINAIS           NM_MUNICIPIO SG_UF
0              0.096215          GUAJARA MIRIM    RO
1              0.215437            PORTO VELHO    RO
2              0.275221              JI PARANA    RO
3              0.546029              ARIQUEMES    RO
4              0.600619                 CACOAL    RO
...                 ...                    ...   ...
5560           0.717970              VILA RICA    MT
5561           0.703908               COMODORO    MT
5562           0.641010  FIGUEIROPOLIS D OESTE    MT
5563           0.524495      GUARANTA DO NORTE    MT
5564           0.688725               INDIAVAI    MT

[5565 rows x 3 columns]

# Exports

In [45]:
indice_centrao_2002.to_csv('indice_centrao_2002.csv', index=False)
indice_centrao_2006.to_csv('indice_centrao_2006.csv', index=False)
indice_centrao_2010.to_csv('indice_centrao_2010.csv', index=False)
indice_centrao_2014.to_csv('indice_centrao_2014.csv', index=False)
indice_centrao_2018.to_csv('indice_centrao_2018.csv', index=False)
indice_centrao_2022.to_csv('indice_centrao_2022.csv', index=False)

In [2]:
import pandas as pd
indice_centrao_2002 = pd.read_csv('indice_centrao_2002.csv')
indice_centrao_2006 = pd.read_csv('indice_centrao_2006.csv')
indice_centrao_2010 = pd.read_csv('indice_centrao_2010.csv')
indice_centrao_2014 = pd.read_csv('indice_centrao_2014.csv')
indice_centrao_2018 = pd.read_csv('indice_centrao_2018.csv')
indice_centrao_2022 = pd.read_csv('indice_centrao_2022.csv')

In [46]:
# Add a year column to each dataframe
indice_centrao_2002['Year'] = 2002
indice_centrao_2006['Year'] = 2006
indice_centrao_2010['Year'] = 2010
indice_centrao_2014['Year'] = 2014
indice_centrao_2018['Year'] = 2018
indice_centrao_2022['Year'] = 2022

# Combine all dataframes into one
panel_data = pd.concat([indice_centrao_2002, indice_centrao_2006, indice_centrao_2010, indice_centrao_2014, indice_centrao_2018, indice_centrao_2022])

# Reset index
panel_data = panel_data.reset_index(drop=True)

panel_data

       QT_VOTOS_NOMINAIS           NM_MUNICIPIO SG_UF  Year
0               0.096215          GUAJARA MIRIM    RO  2002
1               0.215437            PORTO VELHO    RO  2002
2               0.275221              JI PARANA    RO  2002
3               0.546029              ARIQUEMES    RO  2002
4               0.600619                 CACOAL    RO  2002
...                  ...                    ...   ...   ...
33402           0.299394              VILA RICA    MT  2022
33403           0.095763               COMODORO    MT  2022
33404           0.152947  FIGUEIRÓPOLIS D OESTE    MT  2022
33405           0.383479      GUARANTÃ DO NORTE    MT  2022
33406           0.482345               INDIAVAÍ    MT  2022

[33407 rows x 4 columns]

In [47]:
panel_data.to_csv('panel_data_indice.csv', index=False)